name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.1.0"

      - name: "zip the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/evduty"
          zip evduty.zip -r ./

      - name: "Upload the zip file to the release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/evduty/evduty.zip
